networks:
  nats:
  mysql:

volumes:
  mysql:

services:
  nats:
    image: nats
    # -D : debug | -V : verbose | -c <path>.conf : config
    command: ["-DV", "-c", "/etc/nats/nats.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      # :ro : read-only
      - ./nats.conf:/etc/nats/nats.conf:ro
    networks:
      - nats
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql